# Generated by Django 4.0.4 on 2022-04-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_choice_course_lessons_course_rubric'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='logo',
            field=models.ImageField(default=0, upload_to='static'),
            preserve_default=False,
        ),
    ]
