# Generated by Django 4.0.4 on 2022-04-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_course_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_main',
            field=models.BooleanField(default=0),
        ),
    ]
