# Generated by Django 4.0.4 on 2022-04-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_course_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='show_count',
            field=models.IntegerField(default=0),
        ),
    ]
