# Generated by Django 4.0.4 on 2022-04-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_course_show_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
    ]
