# Generated by Django 4.0.4 on 2022-04-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_course_comment_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='logo',
            field=models.ImageField(default=0, upload_to='static'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='show_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
