# Generated by Django 4.0.4 on 2022-04-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_article_logo_article_show_count_article_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='short_decription',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
