# Generated by Django 4.0.4 on 2022-04-27 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_article_short_decription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='short_decription',
            new_name='short_description',
        ),
    ]
