# Generated by Django 4.0.4 on 2022-04-30 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_article_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=65),
        ),
        migrations.CreateModel(
            name='PaidC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=65)),
                ('lessons', models.IntegerField(default=0)),
                ('logo', models.ImageField(upload_to='static')),
                ('is_main', models.BooleanField(default=0)),
                ('show_count', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.choice')),
            ],
        ),
    ]
