# Generated by Django 4.0.4 on 2022-05-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_course_title_paidc'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='link',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
