# Generated by Django 4.0.4 on 2022-05-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_course_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(default=0, max_length=2000),
            preserve_default=False,
        ),
    ]
