# Generated by Django 4.0.4 on 2022-05-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_shi_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='view',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shi',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
