# Generated by Django 4.0.4 on 2022-05-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_course_view_alter_shi_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='paidc',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
