# Generated by Django 4.0.4 on 2022-05-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_paidc_view'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.AddField(
            model_name='course',
            name='short_description',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PaidC',
        ),
    ]
