# Generated by Django 4.0.4 on 2022-05-28 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_course_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='comment_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_main',
            field=models.BooleanField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='link',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='course',
            name='short_description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='show_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='view',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='shi',
            name='show_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='shi',
            name='view',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
