# Generated by Django 4.0.4 on 2022-05-28 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_profession_alter_course_comment_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profession',
            name='title',
        ),
        migrations.AddField(
            model_name='profession',
            name='logo',
            field=models.ImageField(default=0, upload_to='static'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profession',
            name='short_description',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
