# Generated by Django 4.0.4 on 2022-06-01 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_profile_logo_alter_profile_short_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
